// <auto-generated />
namespace TA_ASP_Kecskek.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddKecskek : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddKecskek));
        
        string IMigrationMetadata.Id
        {
            get { return "202204051627359_AddKecskek"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
